name: Plots

on:
  schedule:
    - cron: '*/5 * * * *'  # Check every 5 minutes
  repository_dispatch:
    types: [make_plots]
  workflow_dispatch:

jobs:
  graphing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pyyaml plotly requests

      # Run Python script
      - name: Run Plotting Python Script
        run: |
          python3 python/plot.py

      - name: Track Changes
        run: |
          git add .

      # Commit and push the results
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git commit -m "Update DNS Monitoring Results"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
